
eureka:
  client:
    enabled: true
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://dev:dev@192.168.1.5:8761/eureka/

spring:
  redis:
    host: 192.168.1.5
    port: 6379
    password: xluniccc
    database: 2
    lettuce:
      pool:
        max-active: 32
        max-wait: 300ms
        max-idle: 16
        min-idle: 8
  rabbitmq:
    publisher-confirms: true
    host: 192.168.1.5
    port: 5672
    username: xl
    password: root
    listener:
      direct:
        acknowledge-mode: manual
      simple:
        acknowledge-mode: manual
    virtual-host: /xl


jetcache:
  statIntervalMinutes: 15
  areaInCacheName: false
  local:
    default:
      type: caffeine
      limit: 100
      keyConvertor: fastjson
      expireAfterWriteInMillis: 100000
  remote:
    default:
      type: redis.lettuce
      keyConvertor: fastjson
      valueEncoder: kryo
      valueDecoder: kryo
      uri: redis://xluniccc@192.168.1.5:6379/3
